# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        name: conventional commit
        stages: [commit-msg]
        args: [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]

  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.4.3.1
    hooks:
      - id: shfmt
        name: shfmt
        pass_filenames: true

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.6
    hooks:
      - id: clang-format
        name: clang-format
        pass_filenames: true

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.16.0
    hooks:
      - id: stylua-github
        name: stylua
        pass_filenames: true
