name: luacassandra

services:
  cassandra:
    image: cassandra:4.0
    environment:
      CASSANDRA_LISTEN_ADDRESS: cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: "[ $$(nodetool -h ::FFFF:127.0.0.1 statusgossip) = running ]"

  cassandra_keyspaces:
    image: cassandra:4.0
    depends_on:
      cassandra:
        condition: service_healthy
    command: ["cqlsh", "cassandra", "-e", "CREATE KEYSPACE IF NOT EXISTS testing WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};"]

  driver:
    build:
      context: ..

